CREATE TABLE IDS(TABLE_NAME VARCHAR(16) NOT NULL PRIMARY KEY,NEXT_ID DECIMAL(30) NOT NULL)
CREATE TABLE MYTABLE(ID VARCHAR(16) NOT NULL PRIMARY KEY,USER_NAME VARCHAR(50),DEPT_NAME VARCHAR(100),POSITION VARCHAR(100),EMAIL_ADDR VARCHAR(100))
CREATE TABLE UIP_EMPLOYEE(NUM VARCHAR(10),NAME VARCHAR(50),BIRTHDATE VARCHAR(20),SEX CHAR(1),TELEPHONE VARCHAR(10),ADDRESS VARCHAR(100),POSTAL VARCHAR(10))
INSERT INTO MYTABLE VALUES('SAMPLE-00115','조준','품질/통합시험팀','사장','j.cho@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00116','김형민','고객사업부문','상무','henrykim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00117','김민주-고객센터','고객센터','부장','minjoo.kim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00118','김영주','모바일플랫폼사업팀','부장','yj.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00119','김영호','서울사업단','부장','kyh@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00120','김정열','커뮤니케이션팀','부장','jykim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00121','김준성','단말기운영관리센터','부장','js.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00122','김진규','카드사업팀','부장','justice.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00123','김현정','서비스기획팀','부장','cindy@t-monet.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00124','김호중','연구개발1팀','부장','hj.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00125','김근호','서비스개발팀','차장','keunhokim@t-monet.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00126','김영철','신사업개발팀(티모넷)','차장','yckim@t-monet.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00127','김재환','모니터링파트','과장','jh2kim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00128','김창모','경영지원','과장','cmkim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00129','김은교','티머니1파트','선임','ekkim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00130','김은아','주간파트','선임','eakim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00131','김경희','SM','이사','kh.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00132','김상기','버스수집시스템 구축','이사','KIRICKI@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00133','김기만','2기 교통카드시스템 구축 프로젝트','부장','km.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00134','김대식','이지인터넷','부장','deasik.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00135','김동국','교통사업관리팀','부장','dkkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00136','김동은','2기 교통카드시스템 구축 프로젝트','부장','kde@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00137','김미경','버스수집시스템 구축','부장','mikkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00138','김민성','이지인터넷','부장','minsung.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00139','김석영','버스수집시스템 구축','부장','nearfield@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00140','김영관','버스수집시스템 구축','부장','ykwankim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00141','김인숙','교통정보팀','부장','insookkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00142','김형식','의정부경전철','부장','sh.kim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00143','김호덕','버스수집시스템 구축','부장','hdkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00144','김효근','해외사업이행팀','부장','hyogeunkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00145','김광태','화이트PJT','차장','white@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00146','김근호','마케팅플랫폼PJT','차장','keunhokim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00147','김기대','지역사업3팀','차장','kd.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00148','김명기','몽골버스시스템 구축PJT','차장','kimmk36@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00149','김문환','2기 교통카드시스템 구축 프로젝트','차장','mh.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00150','김미나','교통사업관리팀','차장','minakim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00151','김민선','사업2팀','차장','mskim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00152','김번수','서비스운영팀','차장','sam@t-monet.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00153','김병철','교통품질혁신팀','차장','bychkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00154','김봉석','해외사업1팀','차장','bs.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00155','김상숙','서비스개발팀','차장','kimss@t-monet.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00156','김세종','버스수집시스템 구축','차장','gazna38@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00157','김수향','SM','차장','sh.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00158','김영국','2기 교통카드시스템 구축 프로젝트','차장','keland@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00159','김영근','버스수집시스템 구축','차장','CAS13@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00160','김영선','모바일사업팀(티모넷)','차장','jijon@t-monet.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00161','김영진','모바일교통상품권PJT','차장','yj.kim02@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00162','김영철','버스수집시스템 구축','차장','CAS09@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00163','김용관','Smart Mobility팀','차장','piterkim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00164','김원래','9호선 2단계','차장','pachem.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00165','김은영','교통정보팀','차장','soysoe@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00166','김응민','해외사업1팀','차장','eungmin.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00167','김인배','교통정보팀','차장','inbkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00168','김재수','버스수집시스템 구축','차장','CAS12@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00169','김정','경영지원팀','차장','j.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00170','김정현','교통정보팀','차장','jeonghyonkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00171','김종석','고속버스프로젝트','차장','js.kim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00172','김주훈','모바일교통상품권PJT','차장','jhkim2@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00173','김중대','버스수집시스템 구축','차장','CAS08@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00174','김진산','교통품질혁신팀','차장','kimjsan@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00175','김진호','연구개발2팀','차장','jinho.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00176','김현민','SM','차장','modern93@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00177','김훈철','기술지원팀','차장','hc.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00178','김휘일','Smart Mobility팀','차장','hikim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00179','김경덕','알리페이연동PJT','과장','kdkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00180','김경재','지역사업3팀','과장','kjkim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00181','김곤','VDI 구축 프로젝트','과장','VDI_Admin@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00182','김광호','스마트유통','과장','kh1.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00183','김광호','교통정보팀','과장','lord815@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00184','김남일','고속버스 발권고도화 프로젝트','과장','nikimkr@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00185','김도균','Smart Payment & Mobile팀','과장','dk.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00186','김동민','국토부표준ID 적용 PJT','과장','sootdeng@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00187','김동운','버스수집시스템 구축','과장','techdoll@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00188','김동진','Payment & Platform 시스템팀','과장','dj.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00189','김동한','몽골버스시스템 구축PJT','과장','dhkim01@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00190','김동회','고속버스 발권고도화 프로젝트','과장','dhkim5@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00191','김명철','단말기센터시스템팀','과장','mc.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00192','김문숙','교통임베디드팀','과장','kms@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00193','김민수','9호선 2단계','과장','armada@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00194','김민수','고속버스 발권고도화 프로젝트','과장','mskim111@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00195','김병국','대전지하철 무임카드 적용','과장','littled007@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00196','김병현','임시TFT(COP전용)','과장','bh.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00197','김삼렬','버스수집시스템 구축','과장','samuelkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00198','김상엽','고속버스프로젝트','과장','sy.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00199','김성윤','단말기센터시스템팀','과장','sungyoonkim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00200','김성진','Payment & Platform 시스템팀','과장','sj.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00201','김성현','트인기술','과장','shkim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00202','김성현','교통정보팀','과장','agfly23@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00203','김세준','지역사업1팀','과장','sjkim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00204','김소영','버스수집시스템 구축','과장','shiloah1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00205','김수강','교통정보팀','과장','infidel@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00206','김수정','교통임베디드팀','과장','sjice80@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00207','김승현','교통정보팀','과장','gosig@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00208','김일','교통정보팀','과장','kimil78@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00209','김재석','지역사업1팀','과장','jaesuk.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00210','김재일','스마트유통','과장','ji.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00211','김재헌','교통정보팀','과장','jaehunkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00212','김재환','PMO','과장','ithing.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00213','김정한','PMO','과장','brian.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00214','김진섭','버스수집시스템 구축','과장','codikodi@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00215','김진영','경영기획팀','과장','jy.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00216','김진찬','마케팅플랫폼PJT','과장','jckim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00217','김찬우','알리페이 고도화','과장','chanu@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00218','김태성','기타 SI','과장','ts.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00219','김태완','모바일교통상품권PJT','과장','tw.kim15@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00220','김현석','9호선 2단계','과장','nuri97@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00221','김현일','모바일사업팀(티모넷)','과장','hikim1@t-monet.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00222','김현진','고속버스프로젝트','과장','anice@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00223','김건형','교통정보팀','대리','kimghyung@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00224','김경욱','연구개발2팀','대리','kw.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00225','김규석','교통정보팀','대리','kyusuekim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00226','김대영','교통정보팀','대리','dykim3@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00227','김동완','경영지원팀','대리','dw.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00228','김만재','페이먼트인프라사업팀','대리','mjkim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00229','김무준','통합정산시스템팀','대리','mj.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00230','김미사','교통임베디드팀','대리','misa@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00231','김미진','대전지하철 무임카드 적용','대리','mj7813@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00232','김민수','마케팅플랫폼PJT','대리','wangpo632@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00233','김민주','지역사업2팀','대리','minjookim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00234','김민지','교통정보팀','대리','kimmj@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00235','김병준','SM','대리','bj.kkim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00236','김빛나','교통임베디드팀','대리','binnakim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00237','김성근','2기 교통카드시스템 구축 프로젝트','대리','drksk@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00238','김수환','Payment & Platform 시스템팀','대리','simon.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00239','김안나','모바일플랫폼사업팀','대리','an.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00240','김애녹','Smart Payment & Mobile팀','대리','en.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00241','김영진','교통정보고도화프로젝트','대리','yj.kim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00242','김용진','모바일플랫폼사업팀','대리','yongjin.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00243','김용현','교통임베디드팀','대리','kimyonghyun@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00244','김유경','교통정보팀','대리','yookyung@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00245','김재호','국토부표준ID 적용 PJT','대리','honama99@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00246','김종화','기타 SI','대리','jh.kim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00247','김주희','교통카드시스템팀','대리','no1jhkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00248','김진주','커뮤니케이션팀','대리','jj.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00249','김진희','경영기획팀','대리','jh.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00250','김창현','의정부경전철','대리','chidolekim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00251','김택성','사업1팀','대리','taeksung.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00252','김한','교통임베디드팀','대리','weedskim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00253','김한석','Payment & Platform 시스템팀','대리','hs.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00254','김현동','모바일플랫폼사업팀','대리','hd.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00255','김현성','단말기센터시스템팀','대리','hyskim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00256','김호식','경영지원팀','대리','khs718@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00257','김홍장','지역사업2팀','대리','hongjang.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00258','김효경','교통정보팀','대리','livia88@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00259','김휘경','교통카드시스템팀','대리','maya@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00260','김동환','몽골버스시스템 구축PJT','선임','dhkim0@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00261','김세정','기타 SI','선임','sejeong.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00262','김우성','SM','선임','ws.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00263','김재형','모니터링파트','선임','jhkim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00264','김정선','티머니1파트','선임','jskim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00265','김정연','주간파트','선임','jeongyeon.kim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00266','김현숙','심야/휴일파트','선임','hskim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00267','김현주','가맹점2차','선임','hykim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00268','김경아','티머니2파트','주임','gakim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00269','김민서','티머니1파트','주임','minseo.kim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00270','김진옥','주간파트','주임','jokim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00271','김현희','주간파트','주임','hhkim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00272','김혜정','티머니2차','주임','hjkim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00273','김효정','주간파트','주임','hj2kim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00274','김경민','버스수집시스템 구축','사원','the_rain1426@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00275','김기원','교통정보팀','사원','kw0922@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00276','김동현','사업2팀','사원','donghyun.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00277','김샛별','통합정산시스템팀','사원','sally.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00278','김선준','연구개발1팀','사원','sunjun.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00279','김성우','교통정보팀','사원','ksw83@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00280','김세연','심야/휴일파트','사원','seiyeon.kim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00281','김승권','2기 교통카드시스템 구축 프로젝트','사원','sk.kim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00282','김시진','단말기센터시스템팀','사원','sijin.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00283','김영진','고객지원팀','사원','youngjin.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00284','김용희','고속버스프로젝트','사원','kimyh3@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00285','김유리','교통정보팀','사원','yrkim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00286','김유림','경영기획팀','사원','yr.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00287','김윤진','티머니3파트','사원','yoonjin.kim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00288','김은지','경영지원팀','사원','eunji.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00289','김은지','교통카드시스템팀','사원','eunjikim112@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00290','김정훈','VAN고도화','사원','jhkim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00291','김지수','티머니3파트','사원','jisu.kim@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00292','김지수','개발부서','사원','js.kim2@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00293','김지유','국토부표준ID 적용 PJT','사원','youtian1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00294','김진영','심야/휴일파트','사원','kim.jinyoung@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00295','김진우','SM','사원','jinwookim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00296','김태훈','카드사업팀','사원','th.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00297','김하나','교통사업관리팀','사원','k.hana125@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00298','김하늘','페이먼트인프라사업팀','사원','hn.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00299','김한영','지역사업2팀','사원','hy.kim1@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00300','김현석','경영기획팀','사원','maynard.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00301','김혜수','통합정산시스템팀','사원','hyesu.kim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00302','김진년','사장실직속','자문','jinnkim@koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00303','김기수','9호선 2단계','기타','kskim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00304','김동한','휴대용정산기 개발','기타','dhkim9@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00305','김석일','기타 SI','기타','ksi75@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00306','김연건','9호선 2단계','기타','ygkim@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00307','김온','모바일교통상품권PJT','기타','on.kim0415@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00308','김종섭','9호선 2단계','기타','jskim1@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00309','김진주','주간파트','기타','jinju.kim1@cs-partners.co.kr');
INSERT INTO MYTABLE VALUES('SAMPLE-00310','김찬','사업1팀','기타','chan.kim0417@ptn.koreasmartcard.com');
INSERT INTO MYTABLE VALUES('SAMPLE-00311','김희태','9호선 2단계','기타','htkim1@ptn.koreasmartcard.com');
INSERT INTO IDS VALUES('SAMPLE',312);
INSERT INTO UIP_EMPLOYEE VALUES('4000001','name01','19701201', 'F','263000001','KOREA LGCNS DEVON BATCH', '140201');
INSERT INTO UIP_EMPLOYEE VALUES('4000002','name02','19701201', 'M','263000001','KOREA LGCNS DEVON BATCH', '140201');
INSERT INTO UIP_EMPLOYEE VALUES('4000003','name03','19701201', 'F','263000001','KOREA LGCNS DEVON BATCH', '140201');